name: grav-lensing-weak+strong+photo-tngv5aug-ares
prior: /home/droyo/code-darkmatter/v51-inversebench-v3/InverseBench/exps/pretrain/gravlensing-tngv5aug-conditioningv2-fov225-pretrain/ckpts/ckpt_20000.pt
model:
  _target_: inverse_problems.grav_lensing.WeakAndStrongGravLensing
  loss_factor_weak: 0.05
  loss_factor_strong: 0.2
  z_l: 0.507
  fov: 225.0
  noise_profile: traditional
  shear_filename: /home/droyo/code-darkmatter/v0-datasets/ares/ares_weak_lensing.npy
  strong_lenses_file: /home/droyo/code-darkmatter/v0-datasets/ares/ares_strong_lenses_fov225.pkl
  likelihood_reference: /home/droyo/code-darkmatter/v0-datasets/ares/ares_ll_ref.pt
  unnorm_scale: 1.0
  unnorm_shift: 0.0

data:
  _target_: training.dataset.TNGv5
  root_convergence: /home/droyo/code-darkmatter/v0-datasets/ares/ares_kappa_surfdensity_fov225.npy
  root_photometry: /home/droyo/code-darkmatter/v0-datasets/ares/ares_f125606814_flux.npy
  # root_photometry: /home/droyo/code-darkmatter/v0-datasets/hera_v_band_proxy_fov225.npy
  resolution: 512
  compute_strong_lenses: false
  random_flip: false
  zoom_in_out: false
  id_list: 0 # 0,1,2,3

evaluator:
  _target_: eval.GravLensingEvaluator

exp_dir: exps/inference/grav-lensing-weak+strong+photo-tngv5aug-ares
