name: DPSAdam
method:
  _target_: algo.dps_adam.DPSAdam
  diffusion_scheduler_config:
    num_steps: 1000
    schedule: 'vp'
    timestep: 'vp'
    scaling: 'vp'
  num_steps: 1000
  learning_rate: 1
  tv_regularization_weight: 3e4
  sde: True
