name: Unconditional
method:
  _target_: algo.unconditional.UnconditionalDiffusionSampler
  diffusion_scheduler_config:
    num_steps: 1000
    schedule: 'linear'
    timestep: 'poly-7'
    scaling: 'none'
  sde: False
